### ISSUE TITLE
View all the courses and view a selected course

### ISSUE THREAD

**Issue by dbreon88** [cs130-w21/9#2]
## Epic
A home page that lists out all of the current courses on the application. Users can view all of the courses titles and then select a course to view the courses page which consists of a series of ordered links to the related sources that make up that courses content. 

## User Stories
- [ ] [As a course viewer I want to enter the home page and see a list of all the courses](https://github.com/cs130-w21/9/issues/7)
- [ ] [As a course viewer I want to be able to click on a course to see all the links associated with that course](https://github.com/cs130-w21/9/issues/12)

**Comment by jasonhuan** [comment]
finished in 0fc730d970d532c36592dd306edca7494ee48dbe

route `/courses/` returns array of JSON objects with all courses
route `/courses/{courseName}` returns JSON object of specific course with matching course name
