### ISSUE TITLE
Adding/Loading Data from Firebase&Firestore

### ISSUE THREAD

**Issue by irisgur** [cs130-w21/9#48]
Set up the communication between the our application and the database, so that we can:
1. Write new data to Firestore and
2. Find and retrieve a specified Firebase document upon request

**Comment by jasonhuan** [comment]
added course creation route in commit a7713bd7cf5fc032cc232a35385fe9305f550016
HTTP GET courses route in commit dd9656702bc598f752f916cfdd70ec7128504061
