### ISSUE TITLE
Commenting on a Course

### ISSUE THREAD

**Issue by irisgur** [cs130-w21/9#9]
## User Story
As a course viewer, I want to be able to comment on a course.

## Detailed Description
Course viewers can comment on any course as they wish, and these comments are visible by everyone. People who have checked out the course should be able to comment on the course, so that other people visiting later can have an idea about the course. It is very helpful for users when websites have comment features, because it shows the feedback of other users, which helps them understand what to expect from this course. Especially in an open-source learning platform, people can learn from each other's comments too, and the comments can help other users to choose the most appropriate course for their needs.

## Acceptance Criteria
- [x] Initially, the comment section should be empty.
- [ ] When a new comment is added by a course viewer, it should be visible immediately.
- [ ] When there are multiple comments, they should all be visible in the order they were posted.

**Comment by grantrbrts** [comment]
Didn't go through with comments.
